[project]
name = "summarizer-app"
version = "0.1.0"
description = "PDF summarizer with Groq LLM"
requires-python = ">=3.10"

dependencies = [
    "streamlit>=1.38.0",
    "langchain>=0.3.0",
    "langchain-groq>=0.2.0",
    "langchain-core>=0.3.0",
    "pypdf>=4.3.0",
    "python-dotenv>=1.0.1"
]

[tool.uv]
package = true