name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - uses: actions/checkout@v4

    # Install system dependencies for PDF processing
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y poppler-utils tesseract-ocr

    # Install uv package manager
    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    # Install Python 3.11 using uv
    - name: Set up Python
      run: uv python install 3.11

    # Install all dependencies (runtime + dev groups)
    - name: Install dependencies
      run: uv sync --all-groups

    # Run tests with coverage reporting
    - name: Run tests with coverage
      run: |
        uv run pytest -v tests/ --cov=src/project_summarizer --cov-report=xml
      env:
        GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    # Upload coverage report to Codecov (optional)
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: always()
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
